-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 12:29:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema MitgliederVerwaltungDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS MitgliederVerwaltungDB DEFAULT CHARACTER SET utf8mb4 collate utf8mb4_unicode_ci;
USE MitgliederVerwaltungDB ;

-- -----------------------------------------------------
-- Table TVereine
-- -----------------------------------------------------
DROP TABLE IF EXISTS TVereine ;

CREATE TABLE IF NOT EXISTS TVereine (
  VerID INT NOT NULL AUTO_INCREMENT,
  VerName VARCHAR(45) NULL,
  PRIMARY KEY (VerID))
ENGINE = InnoDB;

ALTER TABLE TVereine AUTO_INCREMENT=1;


-- -----------------------------------------------------
-- Table TMitglieder
-- -----------------------------------------------------
DROP TABLE IF EXISTS TMitglieder ;

CREATE TABLE IF NOT EXISTS TMitglieder (
  MitID INT NOT NULL AUTO_INCREMENT,
  MitVorname VARCHAR(45) NULL,
  MitNachname VARCHAR(45) NULL,
  MitGeburtstag DATE NULL,
  VerID INT NOT NULL,
  PRIMARY KEY (MitID))
ENGINE = InnoDB;

ALTER TABLE TMitglieder AUTO_INCREMENT=101;
-- -----------------------------------------------------
-- Table TAttribute
-- -----------------------------------------------------
DROP TABLE IF EXISTS TAttribute ;

CREATE TABLE IF NOT EXISTS TAttribute (
    AttID INT NOT NULL AUTO_INCREMENT,
    AttName VARCHAR(45) NULL,
    VerID INT NOT NULL,
    PRIMARY KEY (AttID)
)  ENGINE=INNODB;

ALTER TABLE TAttribute AUTO_INCREMENT=1001;
-- -----------------------------------------------------
-- Table TAttributswerte
-- -----------------------------------------------------
DROP TABLE IF EXISTS TAttributswerte ;

CREATE TABLE IF NOT EXISTS TAttributswerte (
  AttID INT NOT NULL,
  MitID INT NOT NULL,
  Wert VARCHAR(45) NULL,
    PRIMARY KEY (AttID,MitID))
ENGINE = InnoDB;

